// This file is auto-generated by Lovable. Do not modify it.
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      // The Lovable auth bridge is browser-only. Keep it out of the server bundle
      // so independent hosts such as Vercel can render /auth and use Supabase
      // email/password auth without constructing the bridge during SSR.
      if (typeof window === "undefined") {
        return { error: new Error("Lovable OAuth is only available in the browser.") };
      }

      const { createLovableAuth } = await import("@lovable.dev/cloud-auth-js");
      const lovableAuth = createLovableAuth();
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
