/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedEntryRouteImport } from './routes/_authenticated/entry'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShopAiRouteImport } from './routes/_authenticated/shop-ai'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as ApiWebhooksAutoflowRouteImport } from './routes/api/webhooks/autoflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntryRoute = AuthenticatedEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopAiRoute = AuthenticatedShopAiRouteImport.update({
  id: '/shop-ai',
  path: '/shop-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWebhooksAutoflowRoute = ApiWebhooksAutoflowRouteImport.update({
  id: '/api/webhooks/autoflow',
  path: '/api/webhooks/autoflow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/board': typeof AuthenticatedBoardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hub': typeof AuthenticatedHubRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop-ai': typeof AuthenticatedShopAiRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/tv': typeof AuthenticatedTvRoute
  '/api/webhooks/autoflow': typeof ApiWebhooksAutoflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/board': typeof AuthenticatedBoardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hub': typeof AuthenticatedHubRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop-ai': typeof AuthenticatedShopAiRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/tv': typeof AuthenticatedTvRoute
  '/api/webhooks/autoflow': typeof ApiWebhooksAutoflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/entry': typeof AuthenticatedEntryRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shop-ai': typeof AuthenticatedShopAiRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/api/webhooks/autoflow': typeof ApiWebhooksAutoflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/board'
    | '/entry'
    | '/history'
    | '/hub'
    | '/imports'
    | '/numbers'
    | '/settings'
    | '/shop-ai'
    | '/tools'
    | '/tv'
    | '/api/webhooks/autoflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/board'
    | '/entry'
    | '/history'
    | '/hub'
    | '/imports'
    | '/numbers'
    | '/settings'
    | '/shop-ai'
    | '/tools'
    | '/tv'
    | '/api/webhooks/autoflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/board'
    | '/_authenticated/entry'
    | '/_authenticated/history'
    | '/_authenticated/hub'
    | '/_authenticated/imports'
    | '/_authenticated/numbers'
    | '/_authenticated/settings'
    | '/_authenticated/shop-ai'
    | '/_authenticated/tools'
    | '/_authenticated/tv'
    | '/api/webhooks/autoflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWebhooksAutoflowRoute: typeof ApiWebhooksAutoflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry': {
      id: '/_authenticated/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof AuthenticatedEntryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop-ai': {
      id: '/_authenticated/shop-ai'
      path: '/shop-ai'
      fullPath: '/shop-ai'
      preLoaderRoute: typeof AuthenticatedShopAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/autoflow': {
      id: '/api/webhooks/autoflow'
      path: '/api/webhooks/autoflow'
      fullPath: '/api/webhooks/autoflow'
      preLoaderRoute: typeof ApiWebhooksAutoflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedEntryRoute: typeof AuthenticatedEntryRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopAiRoute: typeof AuthenticatedShopAiRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedEntryRoute: AuthenticatedEntryRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopAiRoute: AuthenticatedShopAiRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWebhooksAutoflowRoute: ApiWebhooksAutoflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
